name: Run Queries

on:
  # manual run
  workflow_dispatch:

jobs:
  create-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '309.0.0'
          project_id: 'uni-table-289806'
          service_account_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDZtuZSZkaf3wN8\nYrro2Sf/NQACponi9ZBAdhafPvI7BaIUVI9g8UhgS8PnlAse58sQD4plccR4cCgI\n9v7HTh70w11+DLstCSHhSCKvbuAHh3WApQ3MpedE+X0RQ3/A2FxkXSB5pwKKT4gW\nPAwdR0g1IyiNTyDPlaLE4BnJeoEG7jPqLQuaEq1PvVxqiGN2G8aC6y0Utq7D8vkX\nAcymAERfUcBEc29F0iegnZL2o29Rbw57Y3cB9SQMLdPBPi/ZkdJ+7aNvdyk7hkSG\nd0JqiufuD1R1hjuqOwBBmXzJFt3xNwWqECus/NtJniS0+3s1ILFqjJyotupBlejt\ndF/y8ko1AgMBAAECggEAGC+V4aSEBwGe4QQU0IZDR7orEKBQpBp0lnyn4bP78+uZ\nyFlmfjX/vNbd4g2TuLC2YcfgL4nWciy/fdN2lUyL6tQDQFwItSWVEnJRjBysnZmC\nR7LOWCQ8D3EJ4E+X0yQWC34++9S+VwAj1ZiBHgWLs39+40fdlMICTY25v6SwzcSW\n+bCIk8FmH1oYivMgjvo+9JdrssP3JDU7TTac+T9SBUQuU4pUzYqxS0oxWz2UP5rf\nP/Q3Rq+dc2+N/iQ6t9t3Nouxai4TTcUI65/VyiaRZorktRyqF1DF2kTbvb4BWQp9\nRkZp8xRCMFJuMIW2bH0dznLLvmWJnbB9D8CcDWuNlwKBgQD/Rn+ggmiMQVrRlkbC\n/m3PIk3BKtr52xMnM84CbJ0a7shQdcbQKSGoIwGgx8AebZGPeSo7UessjjljHUly\nzciDVijpzwI2ETVDQa6taMjfpCd49ZspxqkDEH1q5toKHvhy/W1ddoQ69AzvfIj2\n0m3FOnaLprA0dRreOZBxWw4CDwKBgQDaVRtPIM7BTNNh2IFJwNeDWN2wMT/wwACg\nRngEGz4pXcDHdZ6z5cQSWN1pztyVL8bSTAfbZhif6xBKiPqHEZTqLCE4o04qkbMZ\n9vXJT7xREi41aOiwdF+3658MrRk46V6Txc49pIoytmr8ZlH1aHbR1NGLs04kZOfy\n1iZuVlzjewKBgQCIh0D9LKIT2WRkUdY4tfEu5i7l0DDbjuK4hcl5nHOOEwWJmuQh\nMs5waYCWaB8FZx6BuJDwtwhrhQmGTASbZRoHvE4XdoK9PgjZlsiAsFk220nNNLau\n6jQ8klYxlZQp85R3k7kpUpi4GwzMDTQHplXVNUZvvE/jTnp3PhxVtBhS2wKBgQCD\nqI6vSLllF07g0g4ky4UqT4xfk1NbemzmOZhl4Ye6qi52GRd6pDN4XN4nz/Z0gDsE\n1ZRnWUnAJZ/NUozApnmGPNZLsS6RvQqjvai5nLuSp8P1sS2gOoz9+7gNjNSI3TGL\nKt0TjwVHT3l0er8xna0JG6zA8X9NswusBDdokeuxwQKBgG+H2Grx4yycygo362Zx\nSH3rdT4lcDpmtCZnEmuljDVy/hKi7QVQ/VOux0LiRSypHVooekvMtTOEhk6Z/roP\nPnD1M6CoUvfrvZCr28TpgtSnctc4HFCDZsxz9/IkRLh7cF3Ar31qoPAFalKcHJz/\nhdAoTkbp5j6Bdxk/vV6SGw9u\n-----END PRIVATE KEY-----\n"
          export_default_credentials: true

      - name:
        run: |
          bq --location=US mk \
          --dataset \
          --default_table_expiration 604800 \
          --description "@bitcoke/retroactive-query output for commit ${{ github.sha }}" \
          'uni-table-289806':retroactive_${{ github.sha }}

  run-queries:
    needs: create-dataset
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        schema:
          - file: "./src/01_uniswap_v1_pairs.sql"
          - file: "./src/02_uniswap_v2_pairs.sql"
          - file: "./src/03_uniswap_v2_syncs.sql"
          - file: "./src/04_parsed_v1_logs.sql"
          - file: "./src/05_uniswap_contracts.sql"
          - file: "./src/06_user_query.sql"
          - file: "./src/07_01_liquidity_provider_query_pt_1.sql"
          - file: "./src/07_02_liquidity_provider_query_pt_2.sql"
          - file: "./src/07_03_liquidity_provider_query_pt_3.sql"
          - file: "./src/08_socks.sql"
          - file: "./src/09_all_earnings.sql"
          - file: "./src/10_all_earnings_hexadecimal.sql"
          - file: "./src/11_sanity_checks.sql"

    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '309.0.0'
          project_id: 'uni-table-289806'
          service_account_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDZtuZSZkaf3wN8\nYrro2Sf/NQACponi9ZBAdhafPvI7BaIUVI9g8UhgS8PnlAse58sQD4plccR4cCgI\n9v7HTh70w11+DLstCSHhSCKvbuAHh3WApQ3MpedE+X0RQ3/A2FxkXSB5pwKKT4gW\nPAwdR0g1IyiNTyDPlaLE4BnJeoEG7jPqLQuaEq1PvVxqiGN2G8aC6y0Utq7D8vkX\nAcymAERfUcBEc29F0iegnZL2o29Rbw57Y3cB9SQMLdPBPi/ZkdJ+7aNvdyk7hkSG\nd0JqiufuD1R1hjuqOwBBmXzJFt3xNwWqECus/NtJniS0+3s1ILFqjJyotupBlejt\ndF/y8ko1AgMBAAECggEAGC+V4aSEBwGe4QQU0IZDR7orEKBQpBp0lnyn4bP78+uZ\nyFlmfjX/vNbd4g2TuLC2YcfgL4nWciy/fdN2lUyL6tQDQFwItSWVEnJRjBysnZmC\nR7LOWCQ8D3EJ4E+X0yQWC34++9S+VwAj1ZiBHgWLs39+40fdlMICTY25v6SwzcSW\n+bCIk8FmH1oYivMgjvo+9JdrssP3JDU7TTac+T9SBUQuU4pUzYqxS0oxWz2UP5rf\nP/Q3Rq+dc2+N/iQ6t9t3Nouxai4TTcUI65/VyiaRZorktRyqF1DF2kTbvb4BWQp9\nRkZp8xRCMFJuMIW2bH0dznLLvmWJnbB9D8CcDWuNlwKBgQD/Rn+ggmiMQVrRlkbC\n/m3PIk3BKtr52xMnM84CbJ0a7shQdcbQKSGoIwGgx8AebZGPeSo7UessjjljHUly\nzciDVijpzwI2ETVDQa6taMjfpCd49ZspxqkDEH1q5toKHvhy/W1ddoQ69AzvfIj2\n0m3FOnaLprA0dRreOZBxWw4CDwKBgQDaVRtPIM7BTNNh2IFJwNeDWN2wMT/wwACg\nRngEGz4pXcDHdZ6z5cQSWN1pztyVL8bSTAfbZhif6xBKiPqHEZTqLCE4o04qkbMZ\n9vXJT7xREi41aOiwdF+3658MrRk46V6Txc49pIoytmr8ZlH1aHbR1NGLs04kZOfy\n1iZuVlzjewKBgQCIh0D9LKIT2WRkUdY4tfEu5i7l0DDbjuK4hcl5nHOOEwWJmuQh\nMs5waYCWaB8FZx6BuJDwtwhrhQmGTASbZRoHvE4XdoK9PgjZlsiAsFk220nNNLau\n6jQ8klYxlZQp85R3k7kpUpi4GwzMDTQHplXVNUZvvE/jTnp3PhxVtBhS2wKBgQCD\nqI6vSLllF07g0g4ky4UqT4xfk1NbemzmOZhl4Ye6qi52GRd6pDN4XN4nz/Z0gDsE\n1ZRnWUnAJZ/NUozApnmGPNZLsS6RvQqjvai5nLuSp8P1sS2gOoz9+7gNjNSI3TGL\nKt0TjwVHT3l0er8xna0JG6zA8X9NswusBDdokeuxwQKBgG+H2Grx4yycygo362Zx\nSH3rdT4lcDpmtCZnEmuljDVy/hKi7QVQ/VOux0LiRSypHVooekvMtTOEhk6Z/roP\nPnD1M6CoUvfrvZCr28TpgtSnctc4HFCDZsxz9/IkRLh7cF3Ar31qoPAFalKcHJz/\nhdAoTkbp5j6Bdxk/vV6SGw9u\n-----END PRIVATE KEY-----\n"
          export_default_credentials: true

      - name:
        run: |
          cat ${{ matrix.schema.file }} | \
          bq --location=US --dataset_id='uni-table-289806':retroactive_${{ github.sha }} query \
          --parameter='cutoff_timestamp:TIMESTAMP:2020-09-01 00:00:00+00' \
          --parameter='cutoff_block_number:INT64:10771925' \
          --parameter='socks_user_reward:FLOAT64:1000' \
          --parameter='user_reward:FLOAT64:400' \
          --parameter='total_reward:FLOAT64:150000000' \
          --nouse_legacy_sql

